
export const languageOptions = [
  { code: 'en', label: 'English', helper: 'Simple, clear labels' },
  { code: 'te', label: 'తెలుగు', helper: 'సులభమైన పదాలు' },
] as const;

export type AppLanguage = (typeof languageOptions)[number]['code'];
export type TranslationKey = string;
type Params = Record<string, string | number>;

const translations = {
  en: {
    'common.appName': 'MedBridge',
    'common.getStarted': 'Get Started',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.home': 'Home',
    'common.schedule': 'Schedule',
    'common.upload': 'Upload',
    'common.caregiver': 'Caregiver',
    'common.settings': 'Settings',
    'common.review': 'Review',
    'common.today': 'Today',
    'common.sample': 'Sample',
    'common.done': 'Done',
    'common.ready': 'Ready',
    'common.opening': 'Opening',
    'common.preparing': 'Preparing',
    'common.generating': 'Generating',
    'common.scanning': 'Scanning',
    'common.updated': 'Updated',
    'common.active': 'Active',
    'common.reset': 'Reset',
    'common.start': 'Start',
    'common.use': 'Use',
    'common.items': 'Items',
    'common.warnings': 'Warnings',
    'common.clear': 'Clear',
    'common.alert': 'Alert',
    'common.stable': 'Stable',
    'common.uploadedNow': 'Uploaded now',
    'common.issuedToday': 'Issued today',
    'common.allHandled': 'All medicines handled.',
    'common.noPendingItems': 'No pending items.',
    'common.noActivity': 'No activity yet.',
    'common.noPendingDoses': 'No pending doses.',
    'common.noActiveReminders': 'No active reminders.',
    'common.languageEnglish': 'English',
    'common.languageTelugu': 'Telugu',
    'navigation.home': 'Home',
    'navigation.schedule': 'Schedule',
    'navigation.upload': 'Upload',
    'navigation.caregiver': 'Caregiver',
    'navigation.settings': 'Settings',
    'onboarding.chooseLanguage': 'Choose your language',
    'onboarding.welcomeHeadline': 'Simple medicine support',
    'onboarding.welcomeSupport': 'Reminders, schedule, caregiver view.',
    'home.eyebrow': 'Home',
    'home.subtitle': 'Next dose and today\'s status.',
    'home.nextDose': 'Next dose',
    'home.adherence': 'Adherence',
    'home.doneTitle': 'Done',
    'home.doneDetail': 'All medicines handled.',
    'home.usingDemoData': 'Using demo data',
    'home.openingReminder': 'Starting reminder.',
    'upload.eyebrow': 'Upload',
    'upload.title': 'Upload',
    'upload.subtitle': 'Add a clear document.',
    'upload.helper': 'Clear pages work best',
    'upload.sampleTitle': 'Sample',
    'upload.continue': 'Continue',
    'upload.review': 'Review',
    'upload.home': 'Home',
    'upload.openingSample': 'Opening sample document.',
    'upload.cameraTitle': 'Take Photo',
    'upload.cameraDetail': 'Use the phone camera for a clear printed prescription.',
    'upload.imageTitle': 'Upload Image',
    'upload.imageDetail': 'Choose a prescription photo already saved on the phone.',
    'upload.pdfTitle': 'Upload PDF',
    'upload.pdfDetail': 'Use a discharge summary or typed hospital medicine sheet.',
    'upload.documentTitle': 'Discharge Summary Sample',
    'upload.documentSummary': 'Printed discharge instructions with 4 medicine lines and one unclear entry.',
    'extraction.eyebrow': 'Review',
    'extraction.loadingTitle': 'Extracting',
    'extraction.loadingDetail': 'Reading medicine lines.',
    'extraction.scanningDetail': 'Preparing medicine list.',
    'extraction.title': 'Extraction',
    'extraction.subtitle': 'Check detected lines.',
    'extraction.readyDetail': 'Review before schedule.',
    'extraction.detected': 'Detected',
    'extraction.nothingTitle': 'Nothing detected',
    'extraction.nothingDetail': 'No medicine lines found.',
    'extraction.reviewAction': 'Review',
    'review.eyebrow': 'Review',
    'review.title': 'Medicines',
    'review.subtitle': 'Confirm before schedule.',
    'review.confirmed': 'Confirmed',
    'review.needsReview': 'Needs review',
    'review.dosage': 'Dosage',
    'review.timing': 'Timing',
    'review.duration': 'Duration',
    'review.food': 'Food',
    'review.missingDosage': 'Missing dosage',
    'review.timingUnclear': 'Timing unclear',
    'review.editedNote': 'Edited locally for demo review.',
    'review.generatingDetail': 'Creating schedule.',
    'review.readyDetail': 'Schedule created.',
    'review.generate': 'Generate',
    'review.confirm': 'Confirm',
    'review.edit': 'Edit',
    'review.remove': 'Remove',
    'schedule.eyebrow': 'Schedule',
    'schedule.title': 'Schedule',
    'schedule.subtitle': 'Morning, afternoon, night.',
    'schedule.nextDose': 'Next dose',
    'schedule.reminder': 'Reminder',
    'schedule.updated': 'Updated',
    'schedule.doneTitle': 'Done',
    'schedule.doneDetail': 'All medicines handled.',
    'schedule.openingReminder': 'Starting reminder.',
    'reminder.eyebrow': 'Reminder',
    'reminder.emptyTitle': 'No reminder',
    'reminder.emptySubtitle': 'Nothing active now.',
    'reminder.emptyDetail': 'All active doses have been handled.',
    'reminder.title': 'Medicine time',
    'reminder.subtitle': 'Choose one action.',
    'reminder.playAgain': 'Play again',
    'reminder.remindAgain': 'Remind me again',
    'reminder.noResponse': 'No response',
    'reminder.takenFeedback': 'Dose marked taken.',
    'reminder.missedFeedback': 'Dose marked missed.',
    'reminder.unconfirmedFeedback': 'Dose marked as unconfirmed.',
    'reminder.repeatFeedback': 'Reminder will repeat.',
    'reminder.voiceReplayed': 'Voice replayed.',
    'reminder.voiceTitle': 'Playing voice reminder',
    'reminder.voiceDetail': '{language} voice prompt simulation active',
    'caregiver.eyebrow': 'Caregiver',
    'caregiver.title': 'Caregiver',
    'caregiver.subtitle': 'Patient status at a glance.',
    'caregiver.followUp': 'Follow-up',
    'caregiver.recent': 'Recent',
    'caregiver.onTrackTitle': 'Stable',
    'caregiver.onTrackDetail': 'All doses on track.',
    'caregiver.adherenceLine': '{percent}% adherence',
    'caregiver.followUpOkay': 'Caregiver okay',
    'caregiver.followUpNeeded': 'Caregiver follow-up',
    'settings.eyebrow': 'Settings',
    'settings.title': 'Settings',
    'settings.subtitle': 'Language and demo mode.',
    'settings.language': 'Language',
    'settings.demoMode': 'Demo mode',
    'settings.noScenario': 'No scenario',
    'settings.appInfoTitle': 'MedBridge',
    'settings.appInfoDetail': 'Mock demo build',
    'demo.title': 'Demo mode',
    'demo.active': 'Demo mode active',
    'demo.ready': 'Demo mode ready',
    'demo.chooseScenario': 'Choose a scenario to guide the MedBridge demo from the dashboard.',
    'demo.activeScenario': 'Active: {name}',
    'demo.smooth.title': 'Smooth',
    'demo.smooth.detail': 'Mostly taken',
    'demo.smooth.summary': 'Smooth Adherence: most doses are taken and the patient is stable.',
    'demo.missed.title': 'Missed',
    'demo.missed.detail': 'Caregiver alert',
    'demo.missed.summary': 'Missed Dose Scenario: caregiver concern is visible because two doses were missed.',
    'demo.noResponse.title': 'No response',
    'demo.noResponse.detail': 'Unconfirmed dose',
    'demo.noResponse.summary': 'No Response Scenario: reminder was not answered and follow-up may be needed.',
    'demo.escalated.title': 'Escalated',
    'demo.escalated.detail': 'Multiple issues',
    'demo.escalated.summary': 'Escalated Caregiver Scenario: the caregiver view clearly shows intervention is needed.',
    'statuses.taken': 'Taken',
    'statuses.missed': 'Missed',
    'statuses.pending': 'Pending',
    'statuses.unconfirmed': 'Unconfirmed',
    'statuses.confirmed': 'Confirmed',
    'statuses.clear': 'Clear',
    'statuses.review': 'Review',
    'statuses.done': 'Done',
    'statuses.alert': 'Alert',
    'statuses.stable': 'Stable',
    'statuses.updated': 'Updated',
    'warnings.missingDosage': 'Missing dosage',
    'warnings.unclearTiming': 'Timing unclear',
    'warnings.possibleDuplicate': 'Possible duplicate',
    'warnings.possiblePrnInstruction': 'Possible PRN instruction',
    'warnings.lowClarityLine': 'Low clarity line',
    'warnings.manualReviewNeeded': 'Manual review needed',
    'medication.tablet': 'tablet',
    'medication.tablets': 'tablets',
    'medication.capsule': 'capsule',
    'medication.capsules': 'capsules',
    'medication.syrup': 'syrup',
    'medication.drops': 'drops',
    'medication.injection': 'injection',
    'medication.beforeFood': 'Before food',
    'medication.afterFood': 'After food',
    'medication.beforeBreakfast': 'Before breakfast',
    'medication.afterBreakfast': 'After breakfast',
    'medication.afterLunch': 'After lunch',
    'medication.afterDinner': 'After dinner',
    'medication.morning': 'Morning',
    'medication.afternoon': 'Afternoon',
    'medication.evening': 'Evening',
    'medication.night': 'Night',
    'medication.morningAndNight': 'Morning and night',
    'medication.onceDaily': 'Once daily',
    'medication.twiceDaily': 'Twice daily',
    'medication.thriceDaily': 'Thrice daily',
    'medication.continueDaily': 'Continue daily',
    'medication.asNeeded': 'As needed',
    'medication.days': '{count} days',
    'messages.usingLocalDemo': 'Using local demo data. Check the MedBridge backend connection.',
    'messages.backendUploadUnavailable': 'Backend upload is unavailable. Using local sample document.',
    'messages.backendScheduleUnavailable': 'Backend schedule sync failed. Using local demo schedule.',
    'messages.doseUpdateOffline': 'Dose update could not reach the backend. Showing local progress only.',
    'messages.demoScheduleReadyTitle': 'Demo schedule ready',
    'messages.demoScheduleReadyDetail': 'The sample document created a medicine plan for today.',
    'messages.reminderOpened': 'Reminder opened',
    'messages.reminderOpenedDetail': 'Reminder opened for {name} at {time}.',
    'messages.voiceReminderReplayed': 'Voice reminder replayed',
    'messages.voiceReminderReplayedDetail': '{name} voice reminder was replayed for the patient.',
    'messages.reminderDelayed': 'Reminder delayed briefly',
    'messages.reminderDelayedDetail': '{name} reminder will appear again soon.',
    'messages.doseMarkedPending': 'Dose marked pending',
    'messages.doseMarkedTaken': 'Dose confirmed taken',
    'messages.doseMarkedMissed': 'Dose marked missed',
    'messages.doseMarkedUnconfirmed': 'Dose left unconfirmed',
    'messages.dosePendingDetail': '{name} is back in the pending list for review.',
    'messages.doseTakenDetail': '{name} was marked taken for {time}.',
    'messages.doseMissedDetail': '{name} was marked missed for {time}.',
    'messages.doseUnconfirmedDetail': 'No response recorded. Dose marked as unconfirmed.',
    'messages.caregiverAlertReason': 'Two or more doses were marked missed today. Caregiver follow-up is recommended.',
    'messages.caregiverWatchReason': 'Multiple doses are still unconfirmed. A caregiver check-in may be helpful.',
    'messages.caregiverOkayReason': 'No caregiver escalation is active right now.',
    'messages.caregiverAlertTriggered': 'Caregiver alert triggered',
    'messages.caregiverWatchTriggered': 'Caregiver watch triggered',
    'messages.scheduleGeneratedTitle': 'Schedule generated',
    'messages.scheduleGeneratedDetail': 'Medicines were converted into a morning, afternoon, and night plan.',
    'messages.oneLineNeedsReview': 'One line may need manual review',
    'messages.detectedLinesSummary': '{count} detected lines ready for review.',
    'messages.smoothHistoryDetail': 'Most doses were marked taken and no caregiver follow-up is needed.',
    'messages.missedHistoryDetail': 'Caregiver attention may be needed because multiple doses were missed.',
    'messages.noResponseHistoryTitle': 'No response recorded',
    'messages.noResponseHistoryDetail': 'Reminder was not answered and doses were marked unconfirmed.',
    'messages.escalatedHistoryTitle': 'Caregiver escalation is active',
    'messages.escalatedHistoryDetail': 'Multiple missed and unconfirmed doses are visible across the day.',
  },
  te: {
    'common.appName': 'మెడ్‌బ్రిడ్జ్',
    'common.getStarted': 'ప్రారంభించండి',
    'common.continue': 'కొనసాగించండి',
    'common.back': 'వెనక్కి',
    'common.close': 'మూసివేయండి',
    'common.home': 'హోమ్',
    'common.schedule': 'షెడ్యూల్',
    'common.upload': 'అప్లోడ్',
    'common.caregiver': 'కేర్‌గివర్',
    'common.settings': 'సెట్టింగ్స్',
    'common.review': 'రివ్యూ',
    'common.today': 'ఈరోజు',
    'common.sample': 'నమూనా',
    'common.done': 'పూర్తి',
    'common.ready': 'సిద్ధం',
    'common.opening': 'తెరుస్తోంది',
    'common.preparing': 'సిద్ధం చేస్తోంది',
    'common.generating': 'షెడ్యూల్ తయారవుతోంది',
    'common.scanning': 'స్కాన్ చేస్తోంది',
    'common.updated': 'అప్డేట్ అయింది',
    'common.active': 'యాక్టివ్',
    'common.reset': 'రీసెట్',
    'common.start': 'ప్రారంభించండి',
    'common.use': 'వాడండి',
    'common.items': 'అంశాలు',
    'common.warnings': 'హెచ్చరికలు',
    'common.clear': 'స్పష్టం',
    'common.alert': 'అలర్ట్',
    'common.stable': 'స్థిరంగా ఉంది',
    'common.uploadedNow': 'ఇప్పుడే అప్లోడ్ చేశారు',
    'common.issuedToday': 'ఈరోజు జారీైంది',
    'common.allHandled': 'ఈరోజు అన్ని మందులు నమోదు అయ్యాయి.',
    'common.noPendingItems': 'పెండింగ్ అంశాలు లేవు.',
    'common.noActivity': 'ఇంకా కార్యచరణ లేదు.',
    'common.noPendingDoses': 'పెండింగ్ డోసులు లేవు.',
    'common.noActiveReminders': 'ప్రస్తుతం రిమైండర్లు లేవు.',
    'common.languageEnglish': 'ఇంగ్లీష్',
    'common.languageTelugu': 'తెలుగు',
    'navigation.home': 'హోమ్',
    'navigation.schedule': 'షెడ్యూల్',
    'navigation.upload': 'అప్లోడ్',
    'navigation.caregiver': 'కేర్‌గివర్',
    'navigation.settings': 'సెట్టింగ్స్',
    'onboarding.chooseLanguage': 'మీ భాషను ఎంచుకోండి',
    'onboarding.welcomeHeadline': 'సులభమైన మందుల సహాయం',
    'onboarding.welcomeSupport': 'రిమైండర్లు, షెడ్యూల్, కేర్‌గివర్ వీక్షణ.',
    'home.eyebrow': 'హోమ్',
    'home.subtitle': 'తదుపరి డోస్ మరియు ఈరోజు స్థితి.',
    'home.nextDose': 'తదుపరి డోస్',
    'home.adherence': 'పాటింపు',
    'home.doneTitle': 'పూర్తి',
    'home.doneDetail': 'ఈరోజు అన్ని మందులు నమోదు అయ్యాయి.',
    'home.usingDemoData': 'డెమో డేటా వాడుతోంది',
    'home.openingReminder': 'రిమైండర్ ప్రారంభమవుతోంది.',
    'upload.eyebrow': 'అప్లోడ్',
    'upload.title': 'అప్లోడ్',
    'upload.subtitle': 'స్పష్టమైన పత్రం జోడించండి.',
    'upload.helper': 'స్పష్టమైన పేజీలు ఉత్తమం',
    'upload.sampleTitle': 'నమూనా',
    'upload.continue': 'కొనసాగించండి',
    'upload.review': 'రివ్యూ',
    'upload.home': 'హోమ్',
    'upload.openingSample': 'నమూనా పత్రం తెరుస్తోంది.',
    'upload.cameraTitle': 'ఫోటో తీయండి',
    'upload.cameraDetail': 'స్పష్టమైన ముద్రిత ప్రిస్క్రిప్షన్ కోసం ఫోన్ కెమెరా వాడండి.',
    'upload.imageTitle': 'చిత్రం అప్లోడ్ చేయండి',
    'upload.imageDetail': 'ఫోన్‌లో ఉన్న ప్రిస్క్రిప్షన్ ఫోటోని ఎంచుకోండి.',
    'upload.pdfTitle': 'PDF అప్లోడ్ చేయండి',
    'upload.pdfDetail': 'డిశ్చార్జ్ సమరీ లేదా టైప్ చేసిన హాస్పిటల్ మందుల షీట్ వాడండి.',
    'upload.documentTitle': 'డిశ్చార్జ్ సమరీ నమూనా',
    'upload.documentSummary': 'ముద్రిత డిశ్చార్జ్ సూచనలు, 4 మందుల లైన్లు, ఒక అస్పష్ట ఎంట్రీ ఉన్నాయి.',
    'extraction.eyebrow': 'రివ్యూ',
    'extraction.loadingTitle': 'ఎక్స్‌ట్రాక్షన్',
    'extraction.loadingDetail': 'మందుల లైన్లు చదువుతోంది.',
    'extraction.scanningDetail': 'మందుల జాబితా సిద్ధం చేస్తోంది.',
    'extraction.title': 'ఎక్స్‌ట్రాక్షన్',
    'extraction.subtitle': 'గుర్తించిన లైన్లు చూడండి.',
    'extraction.readyDetail': 'షెడ్యూల్‌కు ముందు రివ్యూ చేయండి.',
    'extraction.detected': 'గుర్తించినవి',
    'extraction.nothingTitle': 'ఏదీ గుర్తించలేదు',
    'extraction.nothingDetail': 'మందుల లైన్లు కనిపించలేదు.',
    'extraction.reviewAction': 'రివ్యూ',
    'review.eyebrow': 'రివ్యూ',
    'review.title': 'మందులు',
    'review.subtitle': 'షెడ్యూల్‌కు ముందు నిర్ధారించండి.',
    'review.confirmed': 'నిర్ధారించారు',
    'review.needsReview': 'రివ్యూ కావాలి',
    'review.dosage': 'మోతాదు',
    'review.timing': 'సమయం',
    'review.duration': 'రోజులు',
    'review.food': 'ఆహారం',
    'review.missingDosage': 'మోతాదు లేదు',
    'review.timingUnclear': 'సమయం స్పష్టం కాదు',
    'review.editedNote': 'డెమో కోసం లోకల్‌గా సరిచేశారు.',
    'review.generatingDetail': 'షెడ్యూల్ తయారు చేస్తోంది.',
    'review.readyDetail': 'షెడ్యూల్ సిద్ధమైంది.',
    'review.generate': 'షెడ్యూల్ తయారు చేయండి',
    'review.confirm': 'నిర్ధారించండి',
    'review.edit': 'సవరించండి',
    'review.remove': 'తొలగించండి',
    'schedule.eyebrow': 'షెడ్యూల్',
    'schedule.title': 'షెడ్యూల్',
    'schedule.subtitle': 'ఉదయం, మధ్యాహ్నం, రాత్రి.',
    'schedule.nextDose': 'తదుపరి డోస్',
    'schedule.reminder': 'రిమైండర్',
    'schedule.updated': 'అప్డేట్ అయింది',
    'schedule.doneTitle': 'పూర్తి',
    'schedule.doneDetail': 'ఈరోజు అన్ని మందులు నమోదు అయ్యాయి.',
    'schedule.openingReminder': 'రిమైండర్ ప్రారంభమవుతోంది.',
    'reminder.eyebrow': 'రిమైండర్',
    'reminder.emptyTitle': 'రిమైండర్ లేదు',
    'reminder.emptySubtitle': 'ఇప్పుడు యాక్టివ్ రిమైండర్ లేదు.',
    'reminder.emptyDetail': 'యాక్టివ్ డోసులు అన్నీ నమోదు అయ్యాయి.',
    'reminder.title': 'మందు సమయం',
    'reminder.subtitle': 'ఒక చర్య ఎంచుకోండి.',
    'reminder.playAgain': 'మళ్లీ వినిపించండి',
    'reminder.remindAgain': 'మళ్లీ గుర్తుచేయండి',
    'reminder.noResponse': 'స్పందన లేదు',
    'reminder.takenFeedback': 'డోస్ తీసుకున్నట్టు నమోదు అయింది.',
    'reminder.missedFeedback': 'డోస్ మిస్ అయినట్టు నమోదు అయింది.',
    'reminder.unconfirmedFeedback': 'డోస్ నిర్ధారణ కాలేదిగా నమోదు అయింది.',
    'reminder.repeatFeedback': 'రిమైండర్ మళ్లీ వస్తుంది.',
    'reminder.voiceReplayed': 'వాయిస్ మళ్లీ వినిపించబడింది.',
    'reminder.voiceTitle': 'వాయిస్ రిమైండర్ వినిపిస్తోంది',
    'reminder.voiceDetail': '{language} వాయిస్ రిమైండర్ డెమో యాక్టివ్‌లో ఉంది',
    'caregiver.eyebrow': 'కేర్‌గివర్',
    'caregiver.title': 'కేర్‌గివర్',
    'caregiver.subtitle': 'రోగి స్థితి ఒక్క చూపులో.',
    'caregiver.followUp': 'ఫాలో-అప్',
    'caregiver.recent': 'తాజా చరిత్ర',
    'caregiver.onTrackTitle': 'స్థిరంగా ఉంది',
    'caregiver.onTrackDetail': 'అన్ని డోసులు సరైన మార్గంలో ఉన్నాయి.',
    'caregiver.adherenceLine': '{percent}% పాటింపు',
    'caregiver.followUpOkay': 'కేర్‌గివర్ ఆందోళన లేదు',
    'caregiver.followUpNeeded': 'కేర్‌గివర్ ఫాలో-అప్ అవసరం',
    'settings.eyebrow': 'సెట్టింగ్స్',
    'settings.title': 'సెట్టింగ్స్',
    'settings.subtitle': 'భాష మరియు డెమో మోడ్.',
    'settings.language': 'భాష',
    'settings.demoMode': 'డెమో మోడ్',
    'settings.noScenario': 'సన్నివేశం లేదు',
    'settings.appInfoTitle': 'మెడ్‌బ్రిడ్జ్',
    'settings.appInfoDetail': 'మాక్ డెమో బిల్డ్',
    'demo.title': 'డెమో మోడ్',
    'demo.active': 'డెమో మోడ్ యాక్టివ్',
    'demo.ready': 'డెమో మోడ్ సిద్ధంగా ఉంది',
    'demo.chooseScenario': 'డ్యాష్‌బోర్డ్ నుంచి మెడ్‌బ్రిడ్జ్ డెమో సన్నివేశాన్ని ఎంచుకోండి.',
    'demo.activeScenario': 'యాక్టివ్: {name}',
    'demo.smooth.title': 'సులభం',
    'demo.smooth.detail': 'చాలావరకు తీసుకున్నారు',
    'demo.smooth.summary': 'సాఫ్ట్ పాటింపు: ఎక్కువ డోసులు తీసుకున్నారు, రోగి స్థిరంగా ఉన్నారు.',
    'demo.missed.title': 'మిస్ అయినవి',
    'demo.missed.detail': 'కేర్‌గివర్ అలర్ట్',
    'demo.missed.summary': 'మిస్ అయిన డోస్ సన్నివేశం: రెండు డోసులు మిస్ కావడంతో కేర్‌గివర్ ఆందోళన కనిపిస్తుంది.',
    'demo.noResponse.title': 'స్పందన లేదు',
    'demo.noResponse.detail': 'నిర్ధారణ కాలేని డోస్',
    'demo.noResponse.summary': 'స్పందన లేదు సన్నివేశం: రిమైండర్‌కి స్పందన రాలేదు, ఫాలో-అప్ అవసరం కావచ్చు.',
    'demo.escalated.title': 'ఎస్కలేట్ అయింది',
    'demo.escalated.detail': 'అనేక సమస్యలు',
    'demo.escalated.summary': 'ఎస్కలేటెడ్ కేర్‌గివర్ సన్నివేశం: జోక్యం అవసరమని కేర్‌గివర్ వీక్షణ స్పష్టంగా చూపిస్తుంది.',
    'statuses.taken': 'తీసుకున్నారు',
    'statuses.missed': 'మిస్ అయింది',
    'statuses.pending': 'పెండింగ్',
    'statuses.unconfirmed': 'నిర్ధారణ కాలేదు',
    'statuses.confirmed': 'నిర్ధారించారు',
    'statuses.clear': 'స్పష్టం',
    'statuses.review': 'రివ్యూ',
    'statuses.done': 'పూర్తి',
    'statuses.alert': 'అలర్ట్',
    'statuses.stable': 'స్థిరంగా ఉంది',
    'statuses.updated': 'అప్డేట్ అయింది',
    'warnings.missingDosage': 'మోతాదు లేదు',
    'warnings.unclearTiming': 'సమయం స్పష్టం కాదు',
    'warnings.possibleDuplicate': 'డూప్లికేట్ కావచ్చు',
    'warnings.possiblePrnInstruction': 'అవసరమైతే వాడే మందు కావచ్చు',
    'warnings.lowClarityLine': 'లైన్ స్పష్టంగా లేదు',
    'warnings.manualReviewNeeded': 'మాన్యువల్ రివ్యూ అవసరం',
    'medication.tablet': 'మాత్ర',
    'medication.tablets': 'మాత్రలు',
    'medication.capsule': 'క్యాప్సూల్',
    'medication.capsules': 'క్యాప్సూల్లు',
    'medication.syrup': 'సిరప్',
    'medication.drops': 'డ్రాప్స్',
    'medication.injection': 'ఇంజెక్షన్',
    'medication.beforeFood': 'ఆహారం ముందు',
    'medication.afterFood': 'ఆహారం తర్వాత',
    'medication.beforeBreakfast': 'ఉదయం అల్పాహారం ముందు',
    'medication.afterBreakfast': 'ఉదయం అల్పాహారం తర్వాత',
    'medication.afterLunch': 'మధ్యాహ్న భోజనం తర్వాత',
    'medication.afterDinner': 'రాత్రి భోజనం తర్వాత',
    'medication.morning': 'ఉదయం',
    'medication.afternoon': 'మధ్యాహ్నం',
    'medication.evening': 'సాయంత్రం',
    'medication.night': 'రాత్రి',
    'medication.morningAndNight': 'ఉదయం మరియు రాత్రి',
    'medication.onceDaily': 'రోజుకు ఒకసారి',
    'medication.twiceDaily': 'రోజుకు రెండుసార్లు',
    'medication.thriceDaily': 'రోజుకు మూడుసార్లు',
    'medication.continueDaily': 'ప్రతిరోజూ కొనసాగించండి',
    'medication.asNeeded': 'అవసరమైతే',
    'medication.days': '{count} రోజులు',
    'messages.usingLocalDemo': 'లోకల్ డెమో డేటా వాడుతోంది. మెడ్‌బ్రిడ్జ్ బ్యాక్‌ఎండ్ కనెక్షన్ చూడండి.',
    'messages.backendUploadUnavailable': 'బ్యాక్‌ఎండ్ అప్లోడ్ అందుబాటులో లేదు. లోకల్ నమూనా పత్రం వాడుతోంది.',
    'messages.backendScheduleUnavailable': 'బ్యాక్‌ఎండ్ షెడ్యూల్ సింక్ కాలేదు. లోకల్ డెమో షెడ్యూల్ చూపిస్తోంది.',
    'messages.doseUpdateOffline': 'డోస్ అప్డేట్ బ్యాక్‌ఎండ్‌కి వెళ్లలేదు. లోకల్ ప్రోగ్రెస్ మాత్రమే చూపిస్తోంది.',
    'messages.demoScheduleReadyTitle': 'డెమో షెడ్యూల్ సిద్ధమైంది',
    'messages.demoScheduleReadyDetail': 'నమూనా పత్రం ఈరోజు మందుల ప్రణాళికను రూపొందించింది.',
    'messages.reminderOpened': 'రిమైండర్ తెరచారు',
    'messages.reminderOpenedDetail': '{name} కోసం {time}కు రిమైండర్ తెరచారు.',
    'messages.voiceReminderReplayed': 'వాయిస్ రిమైండర్ మళ్లీ వినిపించింది',
    'messages.voiceReminderReplayedDetail': '{name} వాయిస్ రిమైండర్ రోగికి మళ్లీ వినిపించబడింది.',
    'messages.reminderDelayed': 'రిమైండర్ కొద్దిసేపు వాయిదా పడింది',
    'messages.reminderDelayedDetail': '{name} రిమైండర్ కొద్దిసేపట్లో మళ్లీ కనిపిస్తుంది.',
    'messages.doseMarkedPending': 'డోస్ మళ్లీ పెండింగ్‌లో పెట్టారు',
    'messages.doseMarkedTaken': 'డోస్ తీసుకున్నట్టు నిర్ధారించారు',
    'messages.doseMarkedMissed': 'డోస్ మిస్ అయినట్టు నమోదు అయింది',
    'messages.doseMarkedUnconfirmed': 'డోస్ నిర్ధారణ కాలేదిగా ఉంచారు',
    'messages.dosePendingDetail': '{name} మళ్లీ రివ్యూ కోసం పెండింగ్ జాబితాలో ఉంది.',
    'messages.doseTakenDetail': '{name} ను {time} డోస్‌గా తీసుకున్నట్టు గుర్తించారు.',
    'messages.doseMissedDetail': '{name} ను {time} డోస్‌గా మిస్ అయినట్టు గుర్తించారు.',
    'messages.doseUnconfirmedDetail': 'స్పందన నమోదు కాలేదు. డోస్ నిర్ధారణ కాలేదిగా గుర్తించారు.',
    'messages.caregiverAlertReason': 'ఈరోజు రెండు లేదా అంతకంటే ఎక్కువ డోసులు మిస్ అయ్యాయి. కేర్‌గివర్ ఫాలో-అప్ సలహా ఇస్తున్నాం.',
    'messages.caregiverWatchReason': 'అనేక డోసులు ఇంకా నిర్ధారణ కాలేదు. కేర్‌గివర్ ఒకసారి చూసుకోవడం మంచిది.',
    'messages.caregiverOkayReason': 'ఇప్పుడే కేర్‌గివర్ ఎస్కలేషన్ లేదు.',
    'messages.caregiverAlertTriggered': 'కేర్‌గివర్ అలర్ట్ ప్రారంభమైంది',
    'messages.caregiverWatchTriggered': 'కేర్‌గివర్ వాచ్ ప్రారంభమైంది',
    'messages.scheduleGeneratedTitle': 'షెడ్యూల్ రూపొందింది',
    'messages.scheduleGeneratedDetail': 'మందులు ఉదయం, మధ్యాహ్నం, రాత్రి ప్రణాళికగా మార్చబడ్డాయి.',
    'messages.oneLineNeedsReview': 'ఒక లైన్‌కు మాన్యువల్ రివ్యూ అవసరం కావచ్చు',
    'messages.detectedLinesSummary': 'రివ్యూకు {count} లైన్లు సిద్ధంగా ఉన్నాయి.',
    'messages.smoothHistoryDetail': 'చాలా డోసులు తీసుకున్నట్టు నమోదు అయ్యాయి. కేర్‌గివర్ ఫాలో-అప్ అవసరం లేదు.',
    'messages.missedHistoryDetail': 'అనేక డోసులు మిస్ కావడంతో కేర్‌గివర్ శ్రద్ధ అవసరం కావచ్చు.',
    'messages.noResponseHistoryTitle': 'స్పందన నమోదు కాలేదు',
    'messages.noResponseHistoryDetail': 'రిమైండర్‌కు స్పందన రాలేదు. డోసులు నిర్ధారణ కాలేదిగా గుర్తించబడ్డాయి.',
    'messages.escalatedHistoryTitle': 'కేర్‌గివర్ ఎస్కలేషన్ యాక్టివ్‌లో ఉంది',
    'messages.escalatedHistoryDetail': 'రోజంతా అనేక మిస్ అయిన మరియు నిర్ధారణ కాని డోసులు కనిపిస్తున్నాయి.',
  },
} as const;

export function getTranslation(language: AppLanguage, key: TranslationKey, params?: Params): string {
  const template = translations[language][key as keyof (typeof translations)[typeof language]] ?? translations.en[key as keyof typeof translations.en] ?? key;
  if (!params) return template as string;
  return Object.entries(params).reduce((value, [paramKey, paramValue]) => value.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(paramValue)), String(template));
}

const statusKeyMap: Record<string, TranslationKey> = { taken: 'statuses.taken', missed: 'statuses.missed', pending: 'statuses.pending', unconfirmed: 'statuses.unconfirmed', confirmed: 'statuses.confirmed', clear: 'statuses.clear', review: 'statuses.review', done: 'statuses.done', alert: 'statuses.alert', stable: 'statuses.stable', updated: 'statuses.updated' };
const warningKeyMap: Record<string, TranslationKey> = { 'missing-dosage': 'warnings.missingDosage', missing_dosage: 'warnings.missingDosage', 'unclear-timing': 'warnings.unclearTiming', unclear_timing: 'warnings.unclearTiming', 'possible-duplicate': 'warnings.possibleDuplicate', possible_duplicate: 'warnings.possibleDuplicate', 'possible-prn-instruction': 'warnings.possiblePrnInstruction', possible_prn_instruction: 'warnings.possiblePrnInstruction', 'low-clarity-line': 'warnings.lowClarityLine', low_clarity_line: 'warnings.lowClarityLine', 'manual-review-needed': 'warnings.manualReviewNeeded', manual_review_needed: 'warnings.manualReviewNeeded' };
const instructionKeyMap: Record<string, TranslationKey> = { tablet: 'medication.tablet', tablets: 'medication.tablets', capsule: 'medication.capsule', capsules: 'medication.capsules', syrup: 'medication.syrup', drops: 'medication.drops', injection: 'medication.injection', before_food: 'medication.beforeFood', after_food: 'medication.afterFood', before_breakfast: 'medication.beforeBreakfast', after_breakfast: 'medication.afterBreakfast', after_lunch: 'medication.afterLunch', after_dinner: 'medication.afterDinner', morning: 'medication.morning', afternoon: 'medication.afternoon', evening: 'medication.evening', night: 'medication.night', morning_and_night: 'medication.morningAndNight', once_daily: 'medication.onceDaily', twice_daily: 'medication.twiceDaily', thrice_daily: 'medication.thriceDaily', continue_daily: 'medication.continueDaily', as_needed: 'medication.asNeeded' };

function normalizeValue(value: string): string { return value.trim().toLowerCase().replace(/&/g, 'and').replace(/[-\s]+/g, '_'); }
function titleCase(value: string): string { return value.replace(/_/g, ' ').split(' ').filter(Boolean).map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join(' '); }

export function formatStatusLabel(language: AppLanguage, value: string): string { const key = statusKeyMap[normalizeValue(value)]; return key ? getTranslation(language, key) : language === 'en' ? titleCase(value) : value; }
export function formatWarningLabel(language: AppLanguage, value: string): string { const key = warningKeyMap[value] ?? warningKeyMap[normalizeValue(value)]; return key ? getTranslation(language, key) : language === 'en' ? titleCase(value) : value; }
export function formatInstructionLabel(language: AppLanguage, value: string): string {
  const key = instructionKeyMap[normalizeValue(value)];
  if (key) return getTranslation(language, key);
  const dayMatch = value.match(/^(\d+)\s+days$/i);
  if (dayMatch) return getTranslation(language, 'medication.days', { count: dayMatch[1] });
  if (language === 'en') return titleCase(value);
  return value
    .replace(/before breakfast/gi, getTranslation(language, 'medication.beforeBreakfast'))
    .replace(/after breakfast/gi, getTranslation(language, 'medication.afterBreakfast'))
    .replace(/after lunch/gi, getTranslation(language, 'medication.afterLunch'))
    .replace(/after dinner/gi, getTranslation(language, 'medication.afterDinner'))
    .replace(/before food/gi, getTranslation(language, 'medication.beforeFood'))
    .replace(/after food/gi, getTranslation(language, 'medication.afterFood'))
    .replace(/morning and night/gi, getTranslation(language, 'medication.morningAndNight'))
    .replace(/once daily/gi, getTranslation(language, 'medication.onceDaily'))
    .replace(/twice daily/gi, getTranslation(language, 'medication.twiceDaily'))
    .replace(/thrice daily/gi, getTranslation(language, 'medication.thriceDaily'))
    .replace(/continue daily/gi, getTranslation(language, 'medication.continueDaily'))
    .replace(/as needed/gi, getTranslation(language, 'medication.asNeeded'))
    .replace(/morning/gi, getTranslation(language, 'medication.morning'))
    .replace(/afternoon/gi, getTranslation(language, 'medication.afternoon'))
    .replace(/evening/gi, getTranslation(language, 'medication.evening'))
    .replace(/night/gi, getTranslation(language, 'medication.night'))
    .replace(/tablets/gi, getTranslation(language, 'medication.tablets'))
    .replace(/tablet/gi, getTranslation(language, 'medication.tablet'))
    .replace(/capsules/gi, getTranslation(language, 'medication.capsules'))
    .replace(/capsule/gi, getTranslation(language, 'medication.capsule'))
    .replace(/syrup/gi, getTranslation(language, 'medication.syrup'))
    .replace(/drops/gi, getTranslation(language, 'medication.drops'))
    .replace(/injection/gi, getTranslation(language, 'medication.injection'));
}
export function formatUploadMethodLabel(language: AppLanguage, method: 'camera' | 'image' | 'pdf' | 'sample'): string { return getTranslation(language, method === 'camera' ? 'upload.cameraTitle' : method === 'image' ? 'upload.imageTitle' : method === 'pdf' ? 'upload.pdfTitle' : 'common.sample'); }
export function formatUploadMethodDetail(language: AppLanguage, method: 'camera' | 'image' | 'pdf' | 'sample'): string { return getTranslation(language, method === 'camera' ? 'upload.cameraDetail' : method === 'image' ? 'upload.imageDetail' : method === 'pdf' ? 'upload.pdfDetail' : 'upload.documentSummary'); }
export function formatDemoScenarioTitle(language: AppLanguage, scenario: 'smooth' | 'missed' | 'no-response' | 'escalated'): string { const key = scenario === 'no-response' ? 'noResponse' : scenario; return getTranslation(language, `demo.${key}.title`); }
export function formatDemoScenarioDetail(language: AppLanguage, scenario: 'smooth' | 'missed' | 'no-response' | 'escalated'): string { const key = scenario === 'no-response' ? 'noResponse' : scenario; return getTranslation(language, `demo.${key}.detail`); }
export function formatDemoScenarioSummary(language: AppLanguage, scenario: 'smooth' | 'missed' | 'no-response' | 'escalated'): string { const key = scenario === 'no-response' ? 'noResponse' : scenario; return getTranslation(language, `demo.${key}.summary`); }
export function formatLanguageName(language: AppLanguage, code: AppLanguage): string { return getTranslation(language, code === 'te' ? 'common.languageTelugu' : 'common.languageEnglish'); }
export function localizeKnownText(language: AppLanguage, text: string): string {
  if (!text || language === 'en') return text;
  const exactMap: Record<string, string> = {
    'Using local demo data. Check the MedBridge backend connection.': getTranslation(language, 'messages.usingLocalDemo'),
    'Backend upload is unavailable. Using local sample document.': getTranslation(language, 'messages.backendUploadUnavailable'),
    'Backend schedule sync failed. Using local demo schedule.': getTranslation(language, 'messages.backendScheduleUnavailable'),
    'Dose update could not reach the backend. Showing local progress only.': getTranslation(language, 'messages.doseUpdateOffline'),
    'Demo schedule ready': getTranslation(language, 'messages.demoScheduleReadyTitle'),
    'The sample document created a medicine plan for today.': getTranslation(language, 'messages.demoScheduleReadyDetail'),
    'Two or more doses were marked missed today. Caregiver follow-up is recommended.': getTranslation(language, 'messages.caregiverAlertReason'),
    'Multiple doses are still unconfirmed. A caregiver check-in may be helpful.': getTranslation(language, 'messages.caregiverWatchReason'),
    'No caregiver escalation is active right now.': getTranslation(language, 'messages.caregiverOkayReason'),
    'Caregiver alert triggered': getTranslation(language, 'messages.caregiverAlertTriggered'),
    'Caregiver watch triggered': getTranslation(language, 'messages.caregiverWatchTriggered'),
    'Schedule generated': getTranslation(language, 'messages.scheduleGeneratedTitle'),
    'Medicines were converted into a morning, afternoon, and night plan.': getTranslation(language, 'messages.scheduleGeneratedDetail'),
    'One line may need manual review': getTranslation(language, 'messages.oneLineNeedsReview'),
    'Most doses were marked taken and no caregiver follow-up is needed.': getTranslation(language, 'messages.smoothHistoryDetail'),
    'Caregiver attention may be needed because multiple doses were missed.': getTranslation(language, 'messages.missedHistoryDetail'),
    'No response recorded': getTranslation(language, 'messages.noResponseHistoryTitle'),
    'Reminder was not answered and doses were marked unconfirmed.': getTranslation(language, 'messages.noResponseHistoryDetail'),
    'Caregiver escalation is active': getTranslation(language, 'messages.escalatedHistoryTitle'),
    'Multiple missed and unconfirmed doses are visible across the day.': getTranslation(language, 'messages.escalatedHistoryDetail'),
    'Uploaded now': getTranslation(language, 'common.uploadedNow'),
    'Issued today': getTranslation(language, 'common.issuedToday'),
    'Discharge Summary Sample': getTranslation(language, 'upload.documentTitle'),
    'Printed discharge instructions with 4 medicine lines and one unclear entry.': getTranslation(language, 'upload.documentSummary'),
    'All medicines handled.': getTranslation(language, 'common.allHandled'),
    'All doses on track.': getTranslation(language, 'caregiver.onTrackDetail'),
    'No pending items.': getTranslation(language, 'common.noPendingItems'),
    'No activity yet.': getTranslation(language, 'common.noActivity'),
    'No pending doses.': getTranslation(language, 'common.noPendingDoses'),
    'No active reminders.': getTranslation(language, 'common.noActiveReminders'),
    'Dose marked taken.': getTranslation(language, 'reminder.takenFeedback'),
    'Dose marked missed.': getTranslation(language, 'reminder.missedFeedback'),
    'Dose marked unconfirmed.': getTranslation(language, 'reminder.unconfirmedFeedback'),
    'Reminder will repeat.': getTranslation(language, 'reminder.repeatFeedback'),
    'Voice replayed.': getTranslation(language, 'reminder.voiceReplayed'),
    'Playing voice reminder': getTranslation(language, 'reminder.voiceTitle'),
    'Clear pages work best': getTranslation(language, 'upload.helper'),
  };
  if (exactMap[text]) return exactMap[text];
  const detected = text.match(/^(\d+) detected lines ready for review\.$/i); if (detected) return getTranslation(language, 'messages.detectedLinesSummary', { count: detected[1] });
  const reminder = text.match(/^Reminder opened for (.+) at (.+)\.$/); if (reminder) return getTranslation(language, 'messages.reminderOpenedDetail', { name: reminder[1], time: reminder[2] });
  const taken = text.match(/^(.+) was marked taken for (.+)\.$/); if (taken) return getTranslation(language, 'messages.doseTakenDetail', { name: taken[1], time: taken[2] });
  const missed = text.match(/^(.+) was marked missed for (.+)\.$/); if (missed) return getTranslation(language, 'messages.doseMissedDetail', { name: missed[1], time: missed[2] });
  const pending = text.match(/^(.+) is back in the pending list for review\.$/); if (pending) return getTranslation(language, 'messages.dosePendingDetail', { name: pending[1] });
  const replay = text.match(/^(.+) voice reminder was replayed for the patient\.$/); if (replay) return getTranslation(language, 'messages.voiceReminderReplayedDetail', { name: replay[1] });
  const delay = text.match(/^(.+) reminder will appear again soon\.$/); if (delay) return getTranslation(language, 'messages.reminderDelayedDetail', { name: delay[1] });
  return formatInstructionLabel(language, text);
}
export { translations };
